#!/usr/bin/env kubectl apply -f
apiVersion: "stable.agones.dev/v1alpha1"
kind: Fleet
metadata:
  name: udp-server
spec:
  replicas: 2
  template:
    spec:
      ports:
      - name: default
        portPolicy: "Dynamic"
        containerPort: 10001 
      template:
        spec:
          containers:
          - name: simple-udp
            image: gcr.io/omag-demo/example-udp-server:dev 
---
apiVersion: "stable.agones.dev/v1alpha1"
kind: FleetAutoscaler
metadata:
  name: udp-server-autoscaler
spec:
  fleetName: udp-server
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 2
      maxReplicas: 20
