#!/usr/bin/env kubectl apply -f
apiVersion: v1
kind: ConfigMap
metadata:
  name: om-director-data
data:
  director_config.yaml: |
    logging:
      format: text
      level: debug
      source: true 

    debug:
      maxSends: 0
      maxMatchesPerSend: 0
      sleepBetweenSendsSeconds: 30
      
    agones:
      namespace: default
      fleetName: udp-server
      generateName: udp-server-

  ###

  profile.json: |
    {
      "id": "partial",
      "name": "partialv1",
      "imagename": "gcr.io/omag-demo/openmatch-mmf-golang-serving-mmlogic-simple:0.4",
      "host": "om-function",
      "port": 50502,
      
      "properties": {
        "pools": [
          {
            "name": "demoPool",
            "filters": [
              { "name": "demoAttribute", "attribute": "mode.demo", "minv": "0" }
            ]
          }
        ],
        "rosters": [
          {
            "name": "demoRoster",
            "players": [
              { "pool": "demoPool" },
              { "pool": "demoPool" }
            ]
          }
        ]
      }
    }
  
